// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCaRPO7HXCsLSQlO0jVmnWd3xVp3l_tycY',
    appId: '1:407081614553:web:7529c86488c154a15a12c8',
    messagingSenderId: '407081614553',
    projectId: 'wside-94d19',
    authDomain: 'wside-94d19.firebaseapp.com',
    storageBucket: 'wside-94d19.appspot.com',
    measurementId: 'G-BR5Q0K9S5S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk-4owaenTLuJ-2l3MIQ4zsaZDcNhKFNg',
    appId: '1:407081614553:android:641d2ffdbfb00b565a12c8',
    messagingSenderId: '407081614553',
    projectId: 'wside-94d19',
    storageBucket: 'wside-94d19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBP7c1BzUvl89N-8NeEekn835xz9m45HGk',
    appId: '1:407081614553:ios:d06ffab7063a20fd5a12c8',
    messagingSenderId: '407081614553',
    projectId: 'wside-94d19',
    storageBucket: 'wside-94d19.appspot.com',
    iosBundleId: 'com.example.wside',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBP7c1BzUvl89N-8NeEekn835xz9m45HGk',
    appId: '1:407081614553:ios:8731094544cc17835a12c8',
    messagingSenderId: '407081614553',
    projectId: 'wside-94d19',
    storageBucket: 'wside-94d19.appspot.com',
    iosBundleId: 'com.example.wside.RunnerTests',
  );
}
